version: 2
jobs:
  build:
    docker:
    - image: cimg/python:3.12
    steps:
    - checkout
    - run: python --version
    - restore_cache:
        name: Restore Python Cache
        keys:
        # Find a cache corresponding to this specific package-lock.json checksum
        # when this file is changed, this key will fail
        - &pip-key v1-pip-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt" }}
        - v1-pip-{{ arch }}-{{ .Branch }}-
        - v1-pip-{{ arch }}-
    - run: |
        sudo apt-get update && sudo apt-get install -y libpq-dev - already installed

        python -m venv .venv
        source .venv/bin/activate
        pip install -U pip setuptools wheel

        echo "$(pwd)/.venv"
        echo "$(pwd)/.venv/bin"
        echo "$(pip cache dir)"

        pip install -r requirements.dev.txt
        pip install -r requirements.txt
    - save_cache:
        name: Save Python Cache
        key: *pip-key
        paths:
        - ./venv
